// <auto-generated />
using System;
using System.Collections.Generic;
using Balenthiran.LanguageVocab.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balenthiran.LanguageVocab.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706121719_DomainCore")]
    partial class DomainCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balenthiran.LanguageVocab.EntityModels.AnswerLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("Given")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer");

                    b.Property<Guid>("VocabItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabItemId");

                    b.HasIndex("UserId", "VocabItemId");

                    b.ToTable("AnswerLogs");
                });

            modelBuilder.Entity("Balenthiran.LanguageVocab.EntityModels.UserWordStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("TimesCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("TimesSeen")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VocabItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabItemId");

                    b.HasIndex("UserId", "VocabItemId")
                        .IsUnique();

                    b.ToTable("UserWordStates");
                });

            modelBuilder.Entity("Balenthiran.LanguageVocab.EntityModels.VocabItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FrequencyRank")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Glosses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinyinNormalised")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Language", "FrequencyRank");

                    b.HasIndex("Language", "Hanzi")
                        .IsUnique();

                    b.ToTable("VocabItems");
                });

            modelBuilder.Entity("Balenthiran.LanguageVocab.EntityModels.AnswerLogEntity", b =>
                {
                    b.HasOne("Balenthiran.LanguageVocab.EntityModels.VocabItemEntity", "VocabItem")
                        .WithMany()
                        .HasForeignKey("VocabItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabItem");
                });

            modelBuilder.Entity("Balenthiran.LanguageVocab.EntityModels.UserWordStateEntity", b =>
                {
                    b.HasOne("Balenthiran.LanguageVocab.EntityModels.VocabItemEntity", "VocabItem")
                        .WithMany()
                        .HasForeignKey("VocabItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabItem");
                });
#pragma warning restore 612, 618
        }
    }
}
