<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Balenthiran.LanguageVocab.DomainModels/Balenthiran.LanguageVocab.DomainModels.csproj" />
    <ProjectReference Include="../Balenthiran.LanguageVocab.Abstractions/Balenthiran.LanguageVocab.Abstractions.csproj" />
    <ProjectReference Include="../Balenthiran.LanguageVocab.Database/Balenthiran.LanguageVocab.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <EnableDefaultResourceItems>false</EnableDefaultResourceItems>    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
